### ISSUE TITLE
Client establishes and completes creation before handshake fails.

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#12]
### Specification

The client `quiche` connection establishes before the handshake completes. This means that `QUICClient` creation can't know that the TLS handshake has failed before it completes. Currently this is only a problem for the server authenticating the client since the failure will happen after the client connection establishes. 

The problem is not critical however since the connection will soon fail with the expect error. It just causes problems with error reporting related to the life-cycle of the `QUICClient` since the expectation is that the client creation will fail if the connection fails. `TLS` failure is considered part of that.

I'm creating this issue just to track the problem and the upstream issue. 

### Additional context

* Related https://github.com/MatrixAI/js-quic/issues/9#issuecomment-1519298781
* Upstream issue https://github.com/cloudflare/quiche/issues/1489

### Tasks

1. Wait for a response to the upstream issue.

**Comment by CMCDragonkai** [comment]
This is resolved by !26 right?
