### ISSUE TITLE
Check if application protocols are required

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#13]
### Specification

We are providing a list of application protocols for the connection configs. We need to check which of these if any are required. remove unneeded protocols.

### Additional context

* Related #1 

### Tasks

1. Check and removed unneeded application protocols from the connection config.

**Comment by tegefaulkes** [comment]
I think the application protocols are just needed for HTTP related stuff? Its possible we don't need any of them. So if tests succeed with an empty list that that's all we need to do for this issue.

**Comment by tegefaulkes** [comment]
Setting an empty array results in a `TlsFail` and no connection attempt. The minimum needed seems to be that we set at least 1 protocol, I don't think it matters what one we use.

**Comment by tegefaulkes** [comment]
I'll trim the list down to `['http/0.9']`.

**Comment by CMCDragonkai** [comment]
Hold this should be configurable by the end user. It's probably needed for when QUIC would be used for HTTP3.

However are you saying we need a default item in the list...?

In that case, is there an ALPN intended for just basic QUIC data?
