### ISSUE TITLE
Automatically bump `cargo.toml` version to match `package.json`.

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#28]
### Specification

We need the `cargo.toml` version to match the `package.json` version for the CI release/prerelease jobs to work. This needs to happen between the `npm version` command bumping the version number and it committing the tag. There is a `version` script in the `package.json` that is run at that stage.

We need to create a script that will update the `cargo.toml` version to match the new version and make sure it is included in the version commit. 

### Additional context

* Related #1 

### Tasks

1. create a `version` script to update the `cargo.toml` version.
2. Make sure it's included within the version commit.
3. Make sure that the pre-release and release CI jobs are passing and the package is being published.

**Comment by CMCDragonkai** [comment]
Is there a PR for this?

**Comment by tegefaulkes** [comment]
Not yet, I'm going to start on it now.
