### ISSUE TITLE
Change input types to take `string` and `number` instead of `Host` and `Port`

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-quic#36]
### Specification

Input functions should do their validation and throw an exception if they are not correct.

This makes it easier for external users to just pass string and host at the beginning, instead of doing the `as Host` and `as Port`.

We keep the 2 types for the internal operations.

In case we return the information we also continue using the `Host` and `Port` type.

This principle should be the same across `js-quic` and `js-mdns` and any other network libraries we ever factor out.

### Tasks

1. Identify all external functions intended to be used by the end user
2. Convert to `string` and `port` for `Host` and `Port`
3. Throw appropriate exceptions if they are not correct hosts and ports.

**Comment by CMCDragonkai** [comment]
It should be using `toPort` and `fromPort` and `toHost` and `fromHost`. When using `resolveHostname` it should catch any exception and then throw `ErrorQUICHostInvalid`.

We can do the same with `Port` with `ErrorQUICPortInvalid`.

**Comment by tegefaulkes** [comment]
This has been resolved by version  https://github.com/MatrixAI/js-quic/releases/tag/v0.0.13.
