### ISSUE TITLE
Exclude low level events from re-dispatch

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#64]
### Specification

Events such as the `EventQuicStreamSend` and `EventQuicConnectionSend` and any other very low level events needs to be excluded from re-dispatch.

Currently events bubble upwards through re-dispatching at every level . A `QUICStream` event will be created in `QUICStream` and then cloned and dispatched in the `QUICConnection`, `QuicClient`, `QuicServer`, and in `Polykey` through the `NodeConnection` and `NodeConnectionManager`.  As a result a `QUICStream` event can be cloned 4-ish times. This will be a severe performance hit for `send` events which are dispatched for every packet.

To solve this, we need to special case and exclude these events from re-dispatch inside the `QUICConnection` for the `EventQuicStreamSend` and inside the `QUICSocket` for the `EventQUICConnectionSend` event.

### Tasks

1. Exclude all send events from being re-dispatched further than they're needed.
2. Review and do the same for any event that happens often through normal usage. 'Once' events can be ignored here.

**Comment by CMCDragonkai** [comment]
@amydevs this is a performance issue.

**Comment by tegefaulkes** [comment]
This has been addressed by commit 82e4a433ebb5d2af94cefcaf0d0a348873189100.

**Comment by CMCDragonkai** [comment]
All of the above event names should be `QUIC` not `Quic`, I think they were typos.

**Comment by CMCDragonkai** [comment]
In summary:

* JS event target events cannot be redispatched, they have to be cloned and emitted again - this adds alot of work for deeply encapsulated objects.
* We are selectively deciding which events are re-dispatched, and which events are fully encapsulated, and which events are transformed/chained. It's kind of like exceptions catching. We have this same set of operations here too.
