### ISSUE TITLE
Switch `js-quic` over to using flakes

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#99]
### Specification

We still need to convert `js-quic` to using flakes. We just need to replicate how it was done in other repos. I'm making this issue to track the progress for this.

### Tasks

1. Switch over to using flakes

**Comment by CMCDragonkai** [comment]
This is already done. https://github.com/MatrixAI/js-quic/commit/2ba52593ec2be99af4a6e4a06b2668cdf4826dca
